# Docs: https://www.netlify.com/docs/netlify-toml-reference/
[build]
  command = "yarn build"
  functions = "example/dist"
  publish = "example/dist-static/"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/nuxt"
  status = 200
  force = false
